CREATE DATABASE CargoDB;
GO
USE CargoDB;
CREATE TABLE Cargos (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CargoId NVARCHAR(50) NOT NULL,
    VideoPath NVARCHAR(255) NOT NULL,
    LabelText NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);